version: "2.1"
services: 
  nocodb: 
    # depends_on: 
    #   mis-mysql: 
    #     condition: service_healthy
    command: tail -F /dev/null
    hostname: nocodb
    container_name: nocodb
    environment: 
      NC_DB: "mysql2://mis-mysql:3306?u=noco&p=mithra35&d=nocodb"
    # image: "nocodb/nocodb:latest"
    image: kingasiagroup/dev4all:6.6.0.1900R6
    # build:
    #   context: ../../dev-server/docker
    #   dockerfile: Dockerfile
    #   args:
    #     - BUDIBASE_VERSION=0.0.0+dev-docker
    ports: 
      - "18022:22"
      - "80:80"
      - "443:443"
      - "8888:8888"
      - "8080:8080"
      - "13000:13000"
    restart: always
    volumes: 
      - "./vol/nocodb/etc/supervisor:/etc/supervisor:Z"
      - "./vol/nocodb/root:/root:Z"
      - "./vol/nocodb/home:/home:Z"
      - "./vol/nocodb/usr/local/n/versions/node:/usr/local/n/versions/node:Z"
      - "./vol/nocodb/opt/startup:/opt/startup:Z"
      - "./vol/nocodb/nc_data:/usr/app/data"
      - "/workspaces/solution/app/src/nocodb:/workspace/app"
    networks:
      noco-net:
        ipv4_address: 172.75.1.10

  phpmyadmin:
    hostname: phpmyadmin
    container_name: "mis-phpmyadmin-1"
    depends_on:
     - mis-mysql
    image: phpmyadmin
    restart: always
    ports:
      - 15081:80
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=mis-mysql
    networks:
      noco-net:
        ipv4_address: 172.75.1.120
        
  mis-mysql:
    hostname: mis-mysql
    # command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1 --local-infile
    # image: mariadb:10.2.40
    image: mariadb:11.3.2
    # image: mariadb:10.6
    container_name: mis-mysql
    # stop_signal: SIGINT
    # stop_grace_period: 2s
    ports:
      - 3306:3306
    volumes:
      - "./vol/mysql/etc/mysql/conf.d:/etc/mysql/conf.d:Z"
      - "./vol/mysql/initdb.d:/docker-entrypoint-initdb.d:Z"
      - "./vol/mysql/var/lib/mysql:/var/lib/mysql:Z"
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: mithra35
      MYSQL_USER: root
      MYSQL_DATABASE: mysql
      TZ: Asia/Shanghai
    networks:
      noco-net:
        ipv4_address: 172.75.1.121

networks:
  noco-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.75.1.0/24
