version: "2.1"
services: 
  nocodb: 
    # depends_on: 
    #   root_db: 
    #     condition: service_healthy
    # command: tail -F /dev/null
    
    hostname: nocodb
    container_name: nocodb
    environment: 
      NC_DB: "mysql2://root_db:3306?u=noco&p=mithra35&d=root_db"
    # image: "nocodb/nocodb:latest"
    image: kingasiagroup/dev4all:6.6.0.1900R6
    # build:
    #   context: ../../dev-server/docker
    #   dockerfile: Dockerfile
    #   args:
    #     - BUDIBASE_VERSION=0.0.0+dev-docker
    ports: 
      - "18022:22"
      - "80:80"
      - "443:443"
      - "8888:8888"
      - "8080:8080"
      - "13000:13000"
    restart: always
    volumes: 
      - "./vol/nocodb/etc/supervisor:/etc/supervisor:Z"
      - "./vol/nocodb/root:/root:Z"
      - "./vol/nocodb/home:/home:Z"
      - "./vol/nocodb/usr/local/n/versions/node:/usr/local/n/versions/node:Z"
      - "./vol/nocodb/opt/startup:/opt/startup:Z"
      - "./vol/nocodb/nc_data:/usr/app/data"
      - "/workspaces/solution/app/src/nocodb:/workspace/app"

  root_db: 
    environment: 
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: mithra35
      MYSQL_ROOT_PASSWORD: mithra35
      MYSQL_USER: noco
    healthcheck: 
      retries: 10
      test: 
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:8.3.0"
    restart: always
    volumes: 
      - "./vol/nocodb/db_data:/var/lib/mysql"
