version: "2.1"
services: 
  nocodb: 
    # depends_on: 
    #   root_db: 
    #     condition: service_healthy
    command: 
    environment: 
      NC_DB: "mysql2://root_db:3306?u=noco&p=mithra35&d=root_db"
    # image: "nocodb/nocodb:latest"
    image: kingasiagroup/dev4all:6.6.0.1900R6
    # build:
    #   context: ../../dev-server/docker
    #   dockerfile: Dockerfile
    #   args:
    #     - BUDIBASE_VERSION=0.0.0+dev-docker
    ports: 
      - "18080:8080"
    restart: always
    volumes: 
      - "./vol/nocodb/nc_data:/usr/app/data"
      # - "/workspaces/ap-server/src/nocodb:/workspace/app"

  root_db: 
    environment: 
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: mithra35
      MYSQL_ROOT_PASSWORD: mithra35
      MYSQL_USER: noco
    healthcheck: 
      retries: 10
      test: 
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:8.3.0"
    restart: always
    volumes: 
      - "./vol/nocodb/db_data:/var/lib/mysql"
