
CREATE DATABASE IF NOT EXISTS nocodb CHARACTER SET "utf8" COLLATE "utf8_general_ci";
CREATE DATABASE IF NOT EXISTS mytest CHARACTER SET "utf8" COLLATE "utf8_general_ci";

--  ALTER USER 'root'@'%' IDENTIFIED BY 'mithra35';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'mithra35';
CREATE USER IF NOT EXISTS 'noco'@'%' IDENTIFIED BY 'mithra35';
CREATE USER IF NOT EXISTS 'mytest'@'%' IDENTIFIED BY 'mithra35';
CREATE USER IF NOT EXISTS 'ccbruce'@'%' IDENTIFIED BY 'mithra35';

-- GRANT ALL PRIVILEGES ON *.* TO 'ccbrue'@'%';
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'noco'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'ccbruce'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'mytest'@'%';

FLUSH PRIVILEGES;
